apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: llama2-70b-bf16-tp4-pp4-gbs128-ckpt0-n32 
  namespace: default
spec: 
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
          labels:
            scitix.ai/topo-aware-in-node: "true"
        spec: &job-spec
          containers:
          - args:
            - "export NODE_RANK=$RANK && unset RANK && \
               git clone --recursive https://github.com/sallylxl/deep_learning_examples.git -b bugfix/data_dir /workspace/deep_learning_examples && \
               DEEP_LEARNING_EXAMPLES_DIR=/workspace/deep_learning_examples \
               BASE_RESULTS_DIR=/workspace/deep_learning_examples/results  \
               GBS=128 MBS=1 PP=4 TP=4 CP=0 MAX_STEPS=128 RUN_ID=0 \
               ENABLE_CKPT=0 UB_TP_COMM_OVERLAP=0 NFS=False \
               bash /workspace/deep_learning_examples/training/nemo/llm/llama2_70b_bf16/run_nemo_llama2_70b_bf16.sh"
            command:
            - /usr/bin/env
            - bash
            - -c
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TZ
              value: CST-8
            image: registry-ap-southeast.scitix.ai/hpc/nemo:24.07
            imagePullPolicy: Always 
            name: pytorch
            resources:
              limits:
                cpu: "80"
                memory: 800Gi
                nvidia.com/gpu: "8"
                rdma/hca_shared_devices_all: "1"
              requests:
                cpu: "80"
                memory: 800Gi
                nvidia.com/gpu: "8"
                rdma/hca_shared_devices_all: "1"
            securityContext:
              capabilities:
                add:
                - IPC_LOCK
            volumeMounts:
            - mountPath: /dev/shm
              name: dev-shm
          volumes:
          - emptyDir:
              medium: Memory
            name: dev-shm
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: scitix.ai/gpu-type
                        operator: In
                        values:
                          - h100nvlink80
    Worker:
      replicas: 3
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
          labels:
            scitix.ai/topo-aware-in-node: "true"
        spec:
          <<: *job-spec
