apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: llama2-13b-bf16-n8-gbs128-ckpt0
  namespace: default
spec: 
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
          labels:
            scitix.ai/topo-aware-in-node: "true"
        spec: &job-spec
          containers:
          - args:
            - "export NODE_RANK=$RANK && unset RANK && \
            DEEP_LEARNING_EXAMPLES_DIR=/workspace/deep_learning_examples \
            bash /workspace/deep_learning_examples/training/nemo/llm/llama2_13b_bf16/run_nemo_llama2_13b_bf16.sh"
            command:
            - /usr/bin/env
            - bash
            - -c
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TZ
              value: CST-8
            image: registry-ap-southeast.scitix.ai/hpc/nemo:24.07
            imagePullPolicy: Always 
            name: pytorch
            resources:
              limits:
                cpu: "80"
                memory: 800Gi
                nvidia.com/gpu: "8"
                rdma/hca_shared_devices_all: "1"
              requests:
                cpu: "80"
                memory: 800Gi
                nvidia.com/gpu: "8"
                rdma/hca_shared_devices_all: "1"
            securityContext:
              capabilities:
                add:
                - IPC_LOCK
            volumeMounts:
            - mountPath: /dev/shm
              name: dev-shm
            - mountPath: /workspace/deep_learning_examples
              name: data
            - mountPath: /models/preset
              name: models
            - mountPath: /datasets/preset
              name: datasets
          volumes:
          - emptyDir:
              medium: Memory
            name: dev-shm
          - hostPath:
              path: /data/scitix/deep_learning_examples
              type: "DirectoryOrCreate"
            name: data
          - hostPath:
              path: /data/scitix/models/preset
              type: "DirectoryOrCreate"
            name: models
          - hostPath:
              path: /data/scitix/datasets/preset
              type: "DirectoryOrCreate"
            name: datasets
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: scitix.ai/gpu-type
                        operator: In
                        values:
                          - h100nvlink80
    Worker:
      replicas: 0
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
          labels:
            scitix.ai/topo-aware-in-node: "true"
        spec:
          <<: *job-spec
