apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: mega-lm-gpt3-175b-n32
  namespace: default
spec: 
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec: &job-spec
          containers:
          - args:
            - "sleep 1 && export NODE_RANK=$RANK &&  unset RANK && export CUDA_DEVICE_MAX_CONNECTIONS=1 && \
               cd /workspace/deep_learning_examples/training/Megatron-LM && \ 
               GBS=128 GPT3_MODEL_SIZE=175b LOG_INTERVAL=1 bash gpt3.sh"
               #bash examples/gpt3/train_gpt3_175b_distributed.sh"
            command:
            - /usr/bin/env
            - bash
            - -c
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TZ
              value: CST-8
            - name: UCX_ALLOC
              value: "md,mmap,heap"
            - name:  UCX_MM_HUGETLB_MODE
              value: "n"
            - name: NCCL_IB_QPS_PER_CONNECTION
              value: "2"
            - name: NCCL_NVLS_ENABLE
              value: "0"
            - name: NCCL_NET_GDR_LEVEL
              value: "3"
            - name: NCCL_IB_TIMEOUT
              value: "22"
            image: registry-ap-southeast.scitix.ai/hpc/ngc_pytorch:24.03-sicl
            imagePullPolicy: Always 
            name: pytorch
            resources:
              limits:
                cpu: "80"
                memory: 800Gi
                nvidia.com/gpu: "8"
                rdma/hca_shared_devices_all: "1"
              requests:
                cpu: "80"
                memory: 800Gi
                nvidia.com/gpu: "8"
                rdma/hca_shared_devices_all: "1"
            securityContext:
              capabilities:
                add:
                - IPC_LOCK
            volumeMounts:
            - mountPath: /dev/shm
              name: dev-shm
            - mountPath: /workspace/deep_learning_examples
              name: data
            - mountPath: /models/preset
              name: models
            - mountPath: /datasets/preset
              name: datasets
          volumes:
          - emptyDir:
              medium: Memory
            name: dev-shm
          - hostPath:
              path: /data/scitix/deep_learning_examples
              type: ""
            name: data
          - hostPath:
              path: /data/scitix/models/preset
              type: ""
            name: models
          - hostPath:
              path: /data/scitix/datasets/preset
              type: ""
            name: datasets
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: scitix.ai/gpu-type
                        operator: In
                        values:
                          - h100nvlink80
    Worker:
      replicas: 3
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
          labels:
            scitix.ai/topo-aware-in-node: "true"
        spec:
          <<: *job-spec
