apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: neva-llama2-13b-chat-bf16-n8-gbs256
  namespace: default
spec: 
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec: &job-spec
          containers:
          - args:
            - "export NODE_RANK=$RANK && unset RANK && \
            DEEP_LEARNING_EXAMPLES_DIR=/workspace/deep_learning_examples \
            BASE_RESULTS_DIR=/workspace/deep_learning_examples/results  \
            PRETRAINED_LLM_PATH=/models/preset/scitix/hf-to-nemo/Llama-2-13b-chat/ \
            PRETRAINED_VISION_ENCODER_PATH=/models/preset/openai/clip-vit-large-patch14-336/ \
            DATASET_DIR=/datasets/preset/liuhaotian/LLaVA-Pretrain-LCS-558K/ \
            RUN_ID=0919t0917 GBS=256 MBS=32 PP=1 TP=8 MAX_STEPS=2170  \
            ENABLE_CKPT=0 UB_TP_COMM_OVERLAP=0 \
            bash /workspace/deep_learning_examples/training/nemo/neva/run_nemo_neva_llama2_13b_chat_bf16.sh"
            command:
            - /usr/bin/env
            - bash
            - -c
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TZ
              value: CST-8
            image: registry-ap-southeast.scitix.ai/hpc/nemo:24.07
            imagePullPolicy: Always 
            name: pytorch
            resources:
              limits:
                cpu: "80"
                memory: 800Gi
                nvidia.com/gpu: "8"
                rdma/hca_shared_devices_all: "1"
              requests:
                cpu: "80"
                memory: 800Gi
                nvidia.com/gpu: "8"
                rdma/hca_shared_devices_all: "1"
            securityContext:
              capabilities:
                add:
                - IPC_LOCK
            volumeMounts:
            - mountPath: /dev/shm
              name: dev-shm
            - mountPath: /tmp
              name: tmp
            - mountPath: /workspace/deep_learning_examples
              name: data
            - mountPath: /models/preset
              name: models
            - mountPath: /datasets/preset
              name: datasets
          volumes:
          - emptyDir:
              medium: Memory
            name: dev-shm
          - hostPath:
              path: /data/scitix/tmp
              type: ""
            name: tmp
          - hostPath:
              path: /data/scitix/deep_learning_examples
              type: "DirectoryOrCreate"
            name: data
          - hostPath:
              path: /data/scitix/models/preset
              type: "DirectoryOrCreate"
            name: models
          - hostPath:
              path: /data/scitix/datasets/preset
              type: "DirectoryOrCreate"
            name: datasets
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: scitix.ai/gpu-type
                        operator: In
                        values:
                          - h100nvlink80
    Worker:
      replicas: 0
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
          labels:
            scitix.ai/topo-aware-in-node: "true"
        spec:
          <<: *job-spec
