apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: neva-llama2-13b-chat-bf16-n32-gbs256-0913t113521
  namespace: default
spec: 
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec: &job-spec
          containers:
          - args:
            - "sleep 1 && export NODE_RANK=$RANK &&  unset RANK && export CUDA_DEVICE_MAX_CONNECTIONS=1 && \
               cd /workspace/deep_learning_examples/training/nemo/neva && export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/workspace/deep_learning_examples/bin && \
               DEEP_LEARNING_EXAMPLES_DIR=/workspace/deep_learning_examples BASE_RESULTS_DIR=/workspace/deep_learning_examples/results \
               PRETRAINED_LLM_PATH=/models/preset/scitix/hf-to-nemo/Llama-2-13b-chat/ \
	       PRETRAINED_VISION_ENCODER_PATH=/models/preset/openai/clip-vit-large-patch14-336/ \
	       DATASET_DIR=/datasets/preset/liuhaotian/LLaVA-Pretrain-LCS-558K/ \
               RUN_ID=0913t113521 GBS=256 MBS=32 PP=1 TP=8 MAX_STEPS=2170 \
               ENABLE_CKPT=0 \
               bash run_nemo_neva_llama2_13b_chat_bf16.sh"
            command:
            - /usr/bin/env
            - bash
            - -c
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TZ
              value: CST-8
            - name: UCX_ALLOC
              value: "md,mmap,heap"
            - name:  UCX_MM_HUGETLB_MODE
              value: "n"
            - name: NCCL_IB_QPS_PER_CONNECTION
              value: "2"
            - name: NCCL_NVLS_ENABLE
              value: "0"
            - name: NCCL_NET_GDR_LEVEL
              value: "3"
            - name: NCCL_IB_TIMEOUT
              value: "22"
            image: registry-ap-southeast.scitix.ai/hpc/nemo:24.07
            imagePullPolicy: Always 
            name: pytorch
            resources:
              limits:
                cpu: "80"
                memory: 800Gi
                nvidia.com/gpu: "8"
                rdma/hca_shared_devices_all: "1"
              requests:
                cpu: "80"
                memory: 800Gi
                nvidia.com/gpu: "8"
                rdma/hca_shared_devices_all: "1"
            securityContext:
              capabilities:
                add:
                - IPC_LOCK
            volumeMounts:
            - mountPath: /dev/shm
              name: dev-shm
            - mountPath: /workspace/deep_learning_examples
              name: data
            - mountPath: /models/preset
              name: models
            - mountPath: /datasets/preset
              name: datasets
            - mountPath: /tmp
              name: tmp 
          volumes:
          - emptyDir:
              medium: Memory
            name: dev-shm
          - hostPath:
              path: /data/scitix/deep_learning_examples
              type: ""
            name: data
          - hostPath:
              path: /data/scitix/models/preset
              type: ""
            name: models
          - hostPath:
              path: /data/scitix/datasets/preset
              type: ""
            name: datasets
          - hostPath:
              path: /data/scitix/tmp
              type: ""
            name: tmp
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: scitix.ai/gpu-type
                        operator: In
                        values:
                          - h100nvlink80
    Worker:
      replicas: 3
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
          labels:
            scitix.ai/topo-aware-in-node: "true"
        spec:
          <<: *job-spec
