apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: alan-deepseek-prefill
  namespace: t-ai-infra-qqxu03
spec:
  leaderWorkerTemplate:
    size: 1
    leaderTemplate:
      metadata:
        labels:
          app: alan-deepseek
          role: prefill-leader
          leaderworkerset.sigs.k8s.io/role: leader
      spec:
        nodeSelector:
          "siflow.scitix.ai/resource-pool-name": hisys-inference
        dnsPolicy: ClusterFirst
        containers:
        - name: sglang-leader
          image: lmsysorg/sglang:v0.5.1.post2-cu126
          command: ["/usr/bin/env","bash","-c"]
          args:
          - |
            set -euxo pipefail
            export POD_IP="$(hostname -i)"
            exec python3 -m sglang.launch_server \
              --port 30000 \
              --host "0.0.0.0" \
              --model-path /data/DeepSeek-R1 \
              --disaggregation-ib-device mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7 \
              --chunked-prefill-size 524288 \
              --page-size 64 \
              --disable-radix-cache \
              --enable-deepep-moe --deepep-mode normal \
              --disaggregation-mode prefill \
              --mem-fraction-static 0.85 --context-length 32768 \
              --tp 8 \
              --dist-init-addr ${LWS_LEADER_ADDRESS}.svc.cluster.local:20102 \
              --nnodes ${LWS_GROUP_SIZE} --node-rank ${LWS_WORKER_INDEX} \
              --trust-remote-code --max-running-requests 1024 \
              --disaggregation-transfer-backend nixl
          env:
          # 这些参数可以花时间看看哪些是可以去掉的，一直没太搞明白cc瑞哥
          - name: GLOO_SOCKET_IFNAME
            value: eth0
          - name: NCCL_SOCKET_IFNAME
            value: eth0
          - name: NCCL_IB_GID_INDEX
            value: "3"
          - name: NCCL_IB_QPS_PER_CONNECTION
            value: "8"
          - name: NCCL_NET_PLUGIN
            value: none
          - name: NCCL_MIN_NCHANNELS
            value: "4"
          - name: SGLANG_SET_CPU_AFFINITY
            value: "true"
          - name: SGL_ENABLE_JIT_DEEPGEMM
            value: "1"
          ports:
          - containerPort: 30000
          - containerPort: 8998   # NIXL bootstrap
          readinessProbe:
            tcpSocket: { port: 30000 }
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            limits:
              nvidia.com/gpu: "8"
          volumeMounts:
          - { name: dshm,  mountPath: /dev/shm }
          - { name: model, mountPath: /data }
        volumes:
        - name: dshm
          emptyDir: { medium: Memory }
        - name: model
          persistentVolumeClaim:
            claimName: siflow-models
    # 1P 不会创建 worker；如不需要可整段删除，如果多个p需要，因此保留
    workerTemplate:
      metadata:
        labels:
          app: alan-deepseek
          role: prefill-worker
          leaderworkerset.sigs.k8s.io/role: worker
      spec:
        nodeSelector:
          "siflow.scitix.ai/resource-pool-name": hisys-inference
        containers:
        - name: noop
          image: busybox
          command: ["sh","-c","sleep 3600000"]
