apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: deepseekr10528-2prefill
  namespace: t-hisys-xlliu
spec:
  leaderWorkerTemplate:
    leaderTemplate:
      metadata:
        annotations:
          k8s.v1.cni.cncf.io/networks: kube-system/rdma0,kube-system/rdma1,kube-system/rdma2,kube-system/rdma3,kube-system/rdma4,kube-system/rdma5,kube-system/rdma6,kube-system/rdma7
        labels:
          role: leader
      spec:
        containers:
        - command:
          - /usr/bin/env
          - bash
          - -c
          args:
          - |-
            echo "LWS_LEADER_ADDRESS=$LWS_LEADER_ADDRESS"
            echo "LWS_GROUP_SIZE=$LWS_GROUP_SIZE"
            echo "LWS_WORKER_INDEX=$LWS_WORKER_INDEX"
            python3 -m sglang.launch_server --port "30000" --host "0.0.0.0" \
            --model-path /mnt/xstorage/model/deepseek-ai/DeepSeek-R1-0528 \
            --disaggregation-ib-device mlx5_0,mlx5_1,mlx5_2,mlx5_3 \
            --chunked-prefill-size "524288" --max-prefill-tokens "32768" \
            --page-size "64" --ep-dispatch-algorithm dynamic --eplb-algorithm deepseek \
            --enable-dp-lm-head --enable-dp-attention --dp-size "16" --disable-radix-cache \
            --enable-deepep-moe --deepep-mode normal --disaggregation-mode prefill \
            --mem-fraction-static "0.7" --context-length "32768" \
            --tp "16" --dist-init-addr $(LWS_LEADER_ADDRESS):20102 \
            --nnodes $(LWS_GROUP_SIZE) --node-rank $(LWS_WORKER_INDEX) \
            --trust-remote-code --ep-num-redundant-experts "32" --moe-dense-tp-size "1" --max-running-requests "1024"
          env:
          - name: NVSHMEM_HCA_PE_MAPPING
            value: "mlx5_0:1:2,mlx5_1:1:2,mlx5_2:1:2,mlx5_3:1:2"
          - name: NVSHMEM_IB_GID_INDEX
            value: "5"
          - name: NVSHMEM_ENABLE_NIC_PE_MAPPING
            value: "1"
          - name: SGLANG_SET_CPU_AFFINITY
            value: "true"
          - name: SGL_ENABLE_JIT_DEEPGEMM
            value: "1"
          - name: NCCL_IB_GID_INDEX
            value: "5"
          - name: NCCL_IB_QPS_PER_CONNECTION
            value: "8"
          - name: NCCL_IB_SPLIT_DATA_ON_QPS
            value: "1"
          - name: NCCL_NET_PLUGIN
            value: none
          - name: NCCL_MIN_NCHANNELS
            value: "4"
          - name: MC_TE_METRIC
            value: "false"
          - name: NCCL_IB_HCA
            value: ^=mlx5_0,mlx5_5,mlx5_6
          - name: LWS_WORKER_INDEX
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['leaderworkerset.sigs.k8s.io/worker-index']
          image: registry-cn-shanghai.siflow.cn/hisys/sglang:latest
          name: sglang-leader
          ports:
          - containerPort: 30000
            protocol: TCP
          readinessProbe:
            periodSeconds: 300
            tcpSocket:
              port: 30000
          resources:
            limits:
              nvidia.com/gpu: "8"
              nvidia.com/rdma0: "1"
              nvidia.com/rdma1: "1"
              nvidia.com/rdma2: "1"
              nvidia.com/rdma3: "1"
              nvidia.com/rdma4: "1"
              nvidia.com/rdma5: "1"
              nvidia.com/rdma6: "1"
              nvidia.com/rdma7: "1"
          # securityContext:
          #   capabilities:
          #     add:
          #     - IPC_LOCK
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /mnt/xstorage/model
            name: model
        nodeSelector:
          unit: "2"
        volumes:
        - emptyDir:
            medium: Memory
          name: dshm
        - hostPath:
            path: /mnt/xstorage/model
          name: model
    restartPolicy: RecreateGroupOnPodRestart
    size: 2
    workerTemplate:
      metadata:
        annotations:
          k8s.v1.cni.cncf.io/networks: kube-system/rdma0,kube-system/rdma1,kube-system/rdma2,kube-system/rdma3,kube-system/rdma4,kube-system/rdma5,kube-system/rdma6,kube-system/rdma7
      spec:
        containers:
        - command:
          - /usr/bin/env
          - bash
          - -c
          args:
          - |-
            echo "LWS_LEADER_ADDRESS=$LWS_LEADER_ADDRESS"
            echo "LWS_GROUP_SIZE=$LWS_GROUP_SIZE"
            echo "LWS_WORKER_INDEX=$LWS_WORKER_INDEX"
            python3 -m sglang.launch_server --port "30000" --host "0.0.0.0" \
            --model-path /mnt/xstorage/model/deepseek-ai/DeepSeek-R1-0528 \
            --disaggregation-ib-device mlx5_0,mlx5_1,mlx5_2,mlx5_3 \
            --chunked-prefill-size "524288" --max-prefill-tokens "32768" \
            --page-size "64" --ep-dispatch-algorithm dynamic --eplb-algorithm deepseek \
            --enable-dp-lm-head --enable-dp-attention --dp-size "16" --disable-radix-cache \
            --enable-deepep-moe --deepep-mode normal --disaggregation-mode prefill \
            --mem-fraction-static "0.7" --context-length "32768" \
            --tp "16" --dist-init-addr $(LWS_LEADER_ADDRESS):20102 \
            --nnodes $(LWS_GROUP_SIZE) --node-rank $(LWS_WORKER_INDEX) \
            --trust-remote-code --ep-num-redundant-experts "32" --moe-dense-tp-size "1" --max-running-requests "1024"
          env:
          - name: SGLANG_SET_CPU_AFFINITY
            value: "true"
          - name: NVSHMEM_HCA_PE_MAPPING
            value: "mlx5_0:1:2,mlx5_1:1:2,mlx5_2:1:2,mlx5_3:1:2"
          - name: NCCL_IB_HCA
            value: ^=mlx5_0,mlx5_5,mlx5_6
          - name: NVSHMEM_IB_TRAFFIC_CLASS
            value: "16"
          - name: NVSHMEM_IB_GID_INDEX
            value: "5"
          - name: NVSHMEM_ENABLE_NIC_PE_MAPPING
            value: "1"
          - name: CUDA_LAUNCH_BLOCKING
            value: "0"
          - name: SGLANG_MOONCAKE_TRANS_THREAD
            value: "8"
          - name: SGL_ENABLE_JIT_DEEPGEMM
            value: "1"
          - name: SGL_CHUNKED_PREFIX_CACHE_THRESHOLD
            value: "0"
          - name: NCCL_IB_GID_INDEX
            value: "5"
          - name: NCCL_IB_QPS_PER_CONNECTION
            value: "8"
          - name: NCCL_IB_SPLIT_DATA_ON_QPS
            value: "1"
          - name: NCCL_NET_PLUGIN
            value: none
          - name: NCCL_MIN_NCHANNELS
            value: "4"
          - name: MC_TE_METRIC
            value: "true"
          - name: LWS_WORKER_INDEX
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['leaderworkerset.sigs.k8s.io/worker-index']
          image: registry-cn-shanghai.siflow.cn/hisys/sglang:latest
          name: sglang-worker
          ports:
          - containerPort: 30001
            protocol: TCP
          resources:
            limits:
              nvidia.com/gpu: "8"
              nvidia.com/rdma0: "1"
              nvidia.com/rdma1: "1"
              nvidia.com/rdma2: "1"
              nvidia.com/rdma3: "1"
              nvidia.com/rdma4: "1"
              nvidia.com/rdma5: "1"
              nvidia.com/rdma6: "1"
              nvidia.com/rdma7: "1"
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /mnt/xstorage/model
            name: model
        nodeSelector:
          unit: "2"
        volumes:
        - emptyDir:
            medium: Memory
          name: dshm
        - hostPath:
            path: /mnt/xstorage/model
          name: model
---
apiVersion: v1
kind: Service
metadata:
  name: deepseekr10528-2prefill-svc
  namespace: t-hisys-xlliu
spec:
  selector:
    leaderworkerset.sigs.k8s.io/name: deepseekr10528-2prefill
    role: leader
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 30000
