apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: deepseek-decode
  namespace: default
spec:
  leaderWorkerTemplate:
    size: 2
    leaderTemplate:
      metadata:
        labels:
          leaderworkerset.sigs.k8s.io/role: leader
          role: decode-leader
      spec:
        hostNetwork: true
        hostIPC: true
        dnsPolicy: ClusterFirstWithHostNet
        nodeSelector:
          "scitix.ai/gpu-type": h20xnvlink141
          "roce.scitix.ai/unit": unit1
        containers:
        - name: sglang-leader
          image: registry-cn-shanghai.siflow.cn/hisys/sglang:v0.5.1.post2-cu126
          securityContext:
            privileged: true
          command: ["/usr/bin/env","bash","-c"]
          args:
          - |-
            echo "LWS_LEADER_ADDRESS=$LWS_LEADER_ADDRESS"
            echo "LWS_GROUP_SIZE=$LWS_GROUP_SIZE"
            echo "LWS_WORKER_INDEX=$LWS_WORKER_INDEX"
            exec python3 -m sglang.launch_server \
              --host "0.0.0.0" \
              --port 30000 \
              --model-path /mnt/models/deepseek-ai/DeepSeek-V3.1-Base \
              --chunked-prefill-size 20480 \
              --page-size 64 \
              --enable-deepep-moe \
              --deepep-mode low_latency \
              --disaggregation-mode decode \
              --mem-fraction-static 0.85 \
              --context-length 32768 \
              --disaggregation-ib-device "mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7" \
              --cuda-graph-max-bs 64 \
              --max-running-requests 2048 \
              --eplb-rebalance-layers-per-chunk 29 \
              --tp-size 16 \
              --dist-init-addr ${LWS_LEADER_ADDRESS}.svc.cluster.local:20102 \
              --nnodes 2 \
              --node-rank 0 \
              --moe-dense-tp-size 1 \
              --trust-remote-code \
              --disaggregation-transfer-backend nixl \
              --enable-dp-attention \
              --enable-dp-lm-head \
              --dp-size 8
          env:
          - name: SGLANG_HOST_IP
            valueFrom: {fieldRef: {fieldPath: status.hostIP}}
          - name: HOST_IP
            valueFrom: {fieldRef: {fieldPath: status.hostIP}}
          - name: MC_TE_METRIC
            value: "true"
          - name: SGL_ENABLE_JIT_DEEPGEMM
            value: "1"
          ports:
          - containerPort: 30000
            protocol: TCP
          readinessProbe:
            initialDelaySeconds: 100
            timeoutSeconds: 300
            periodSeconds: 30
            tcpSocket:
              port: 30000
          resources:
            limits:
              nvidia.com/gpu: "8"
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /mnt
            name: mnt
        volumes:
        - name: dshm
          emptyDir: { medium: Memory }
        - name: mnt
          hostPath:
            path: /mnt/xstorage

    workerTemplate:
      metadata:
        labels:
          role: decode-worker
      spec:
        hostNetwork: true
        hostIPC: true
        dnsPolicy: ClusterFirstWithHostNet
        nodeSelector:
          "scitix.ai/gpu-type": h20xnvlink141
          "roce.scitix.ai/unit": unit1
        containers:
        - name: sglang-worker
          image: registry-cn-shanghai.siflow.cn/hisys/sglang:v0.5.1.post2-cu126
          securityContext:
            privileged: true
          command: ["/usr/bin/env","bash","-c"]
          args:
          - |-
            echo "LWS_LEADER_ADDRESS=$LWS_LEADER_ADDRESS"
            echo "LWS_GROUP_SIZE=$LWS_GROUP_SIZE"
            echo "LWS_WORKER_INDEX=$LWS_WORKER_INDEX"
            exec python3 -m sglang.launch_server \
              --host "0.0.0.0" \
              --port 30000 \
              --model-path /mnt/models/deepseek-ai/DeepSeek-V3.1-Base \
              --chunked-prefill-size 20480 \
              --page-size 64 \
              --enable-deepep-moe \
              --deepep-mode low_latency \
              --disaggregation-mode decode \
              --mem-fraction-static 0.85 \
              --context-length 32768 \
              --disaggregation-ib-device "mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7" \
              --cuda-graph-max-bs 64 \
              --max-running-requests 2048 \
              --tp-size 16 \
              --dist-init-addr ${LWS_LEADER_ADDRESS}.svc.cluster.local:20102 \
              --nnodes ${LWS_GROUP_SIZE} \
              --node-rank ${LWS_WORKER_INDEX} \
              --trust-remote-code \
              --moe-dense-tp-size 1 \
              --disaggregation-transfer-backend nixl \
              --enable-dp-attention \
              --enable-dp-lm-head \
              --dp-size 8

          env:
          - name: SGLANG_HOST_IP
            valueFrom: {fieldRef: {fieldPath: status.hostIP}}
          - name: HOST_IP
            valueFrom: {fieldRef: {fieldPath: status.hostIP}}
          - name: MC_TE_METRIC
            value: "true"
          - name: SGL_ENABLE_JIT_DEEPGEMM
            value: "1"
          ports:
          - containerPort: 30000
            protocol: TCP
          readinessProbe:
            initialDelaySeconds: 100
            timeoutSeconds: 300
            periodSeconds: 30
            tcpSocket:
              port: 30000
          resources:
            limits:
              nvidia.com/gpu: "8"
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /mnt
            name: mnt
        volumes:
        - name: dshm
          emptyDir: { medium: Memory }
        - name: mnt
          hostPath:
            path: /mnt/xstorage

  replicas: 1
  rolloutStrategy:
    type: RollingUpdate
    rollingUpdateConfiguration:
      maxSurge: 0
      maxUnavailable: 1
  startupPolicy: LeaderCreated